# Convenience play to unmount all client filesystems in the right order

- hosts: nfs_client
  become: yes
  tasks:
    - name: Unmount NFS demo client
      command: umount /mnt/lustre
      failed_when: false

- hosts: exporters
  become: yes
  tasks:
    - name: Stop NFS server
      service:
        name: nfs-server
        state: stopped
      failed_when: false

- hosts: clients:admin
  become: yes
  tasks:
    - name: Change client Lustre fileysystem mount state
      tags: mount
      mount:
        src: "{{ lustre_mount_src }}"
        path: "{{ lustre_mount_dir }}"
        fstype: lustre
        state: absent
