---
roles:
- src: git+git@github.com:stackhpc/ansible-role-lustre.git
- src: git+git@github.com:stackhpc/ansible-role-loopdev
- src: git+git@github.com:stackhpc/ansible-role-cluster-nfs
  version: feature/rdma
- src: https://github.com/stackhpc/ansible-node-exporter.git
  version: support-rhel-clones
  name: cloudalchemy.node_exporter
- src: cloudalchemy.blackbox-exporter
- src: cloudalchemy.snmp-exporter
- src: https://github.com/cloudalchemy/ansible-prometheus.git
  version: 4d2c8d742de39e50387e0aa6d5510b21c7451343 # need fix in preceeding commit for rocky
  name: cloudalchemy.prometheus
- src: cloudalchemy.grafana
