- hosts: servers
  tags: servers
  become: yes
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      register: selinux
    
    - name: Install patched kernels for lustre
      import_role:
        name: ansible-role-linux-kernel
      when: lustre_install_type == 'server'
    
    - name: Install latest kernel packages
      yum:
        name: "{{ kernel_pkgs }}"
        state: latest
      when: lustre_install_type == 'patchless-ldiskfs-server'
      vars:
        kernel_pkgs:
          - kernel
          - kernel-devel
          - kernel-headers
          - kernel-tools
          - kernel-tools-libs
          - kernel-tools-libs-devel
      register: kernel_install
      
    - name: Reboot
      reboot:
      when: kernel_install.changed | default('false') or selinux.reboot_required
    
    - name: Update facts after (possible) reboot
      setup:

    - name: Enumerate block devices
      # Note this is done AFTER the reboot as that might reorder devices
      command: "lsblk --noheadings --list --paths --output serial,name"
      register: _lsblk
      changed_when: false

    - name: Map device ids to paths
      set_fact:
        block_device_paths: "{{ dict(_lsblk.stdout_lines | map('regex_replace', '^\\s+\\S+', '') | reject('eq', '') | map('split')) }}" # omits devices without a serial

    - name: Install lustre server
      import_role:
        name: ansible-role-lustre
    
    - name: List NIDs
      tags: checks
      command:
        cmd: lctl list_nids
      register: _lctl_nids
      failed_when: (_lctl_nids.rc != 0) or ('@' not in _lctl_nids.stdout)
      changed_when: false

    - name: List lustre devices
      tags: checks
      command:
        cmd: lctl dl
      register: _lctl_dl
      changed_when: false
    
    - name: Assert server components running
      tags: checks
      assert:
        that: item in _lctl_dl.stdout
        fail_msg: "Did not find '{{ item }}' in lctl dl output"
      loop:
        - UP mgs
        - UP mgc
        - UP mds
        - UP mdt
        - UP ost

- hosts: clients
  tags: clients
  become: yes
  tasks:
    - name: Gather facts from MGS
      setup:
      delegate_to: "{{ groups['servers'][0] }}"
      delegate_facts: True
    
    - name: Install lustre client
      import_role:
        name: ansible-role-lustre
    
    - name: Ensure mount point exists
      file:
        path: "/mnt/{{ lustre_fsname}}"
        state: directory
        # TODO owner, mode

    - name: Mount lustre fileysystem
      mount:
        src: "{{ hostvars[groups['servers'][0]]['ansible_facts']['eth0']['ipv4']['address'] }}@tcp1:/{{ lustre_fsname }}"
        path: /mnt/lustre
        fstype: lustre
        state: "{{ client_mount_state | default('mounted') }}"
